stages:
- name: Publish image wordpress
  steps:
  - publishImageConfig:
      dockerfilePath: ./wordpress/Dockerfile
      buildContext: ./wordpress
      tag: wordpress:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./wordpress/deploy/deployment.yaml
notification: {}

stages:
- name: Publish image mysql
  steps:
  - publishImageConfig:
      dockerfilePath: ./mysql/Dockerfile
      buildContext: ./mysql
      tag: mysql:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./mysql/deploy/deployment.yaml
notification: {}