version: '3.7'

services:

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    volumes: 
      - ./data/db_data:/var/lib/mysql
    ports: 
      - "3306:80"
    command: "--default-authentication-plugin=mysql_native_password"
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  
  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    image: wordpress:latest
    restart: always
    depends_on: 
      - db
    ports: 
      - "80:80"
    volumes: 
      - ./wordpress/app:/var/www/html
    environment: 
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      
volumes:
  db_data: {}
  app: {}